language: java
jdk:
  - openjdk7
after_success:
    - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
   gradle clean check war
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api-key: $GITHUB_KEY
  on:
    tags: true